import { create } from "zustand";
import {
  createEmptyEditorDocument,
  type EditorDocument,
} from "./editorDocument";
import { cloneEditorObject, createDemandZoneObject } from "./objectFactory";

export type Tool =
  | "select"
  | "drone"
  | "gateway"
  | "client"
  | "building"
  | "wall"
  | "tree-zone"
  | "demand-zone";

export type BaseObject = {
  id: string;
  type: Exclude<Tool, "select">;
  x: number;
  y: number;
  label: string;
};

export type DroneObject = BaseObject & {
  type: "drone";
  radioRange: number;
  battery: number;
};

export type GatewayObject = BaseObject & {
  type: "gateway";
  uplink: string;
};

export type ClientObject = BaseObject & {
  type: "client";
  demandClass: string;
};

export type BuildingObject = BaseObject & {
  type: "building";
  width: number;
  height: number;
  attenuation: number;
};

export type WallObject = BaseObject & {
  type: "wall";
  length: number;
  attenuation: number;
};

export type TreeZoneObject = BaseObject & {
  type: "tree-zone";
  radius: number;
  attenuation: number;
};

export type DemandZoneObject = BaseObject & {
  type: "demand-zone";
  radius: number;
  intensity: number;
  autoGenerated?: boolean;
  clientIds?: string[];
  color?: string;
  clusterKey?: string;
};

export type EditorObject =
  | DroneObject
  | GatewayObject
  | ClientObject
  | BuildingObject
  | WallObject
  | TreeZoneObject
  | DemandZoneObject;

type EditorStore = {
  activeTool: Tool;
  setActiveTool: (tool: Tool) => void;

  showDroneRanges: boolean;
  toggleDroneRanges: () => void;

  showClientDroneLinks: boolean;
  toggleClientDroneLinks: () => void;

  selectedObjectId: string | null;
  selectedObjectIds: string[];
  setSelectedObjectId: (id: string | null) => void;
  setSelectedObjectIds: (ids: string[]) => void;
  clearSelection: () => void;

  objects: EditorObject[];
  clipboardObjects: EditorObject[];
  addObject: (object: EditorObject) => void;
  addObjects: (objects: EditorObject[]) => void;

  updateObject: (id: string, patch: Partial<EditorObject>) => void;
  updateObjectsById: (ids: string[], updater: (object: EditorObject) => Partial<EditorObject>) => void;
  removeObject: (id: string) => void;
  removeSelectedObjects: () => void;
  copySelectedObjects: () => void;
  pasteClipboard: () => void;

  densityCellSize: number;
  setDensityCellSize: (value: number) => void;
  densityThreshold: number;
  setDensityThreshold: (value: number) => void;
  autoZoneRadius: number;
  setAutoZoneRadius: (value: number) => void;
  autoZoneIntensity: number;
  setAutoZoneIntensity: (value: number) => void;
  autoDemandZonesEnabled: boolean;
  toggleAutoDemandZones: () => void;

  documentName: string;
  setDocumentName: (name: string) => void;

  resetDocument: () => void;
  replaceFromDocument: (doc: EditorDocument) => void;
  exportToDocument: () => EditorDocument;
};

export function computeAutoDemandZones(state: {
  objects: EditorObject[];
  densityCellSize: number;
  densityThreshold: number;
  autoZoneRadius: number;
  autoZoneIntensity: number;
  autoDemandZonesEnabled: boolean;
}) {
  const palette = [
    "#ef4444",
    "#f97316",
    "#eab308",
    "#22c55e",
    "#06b6d4",
    "#3b82f6",
    "#8b5cf6",
    "#ec4899",
  ];

  function colorForCluster(key: string) {
    let hash = 0;
    for (let index = 0; index < key.length; index += 1) {
      hash = (hash * 31 + key.charCodeAt(index)) >>> 0;
    }

    return palette[hash % palette.length];
  }

  if (!state.autoDemandZonesEnabled) {
    return [] as DemandZoneObject[];
  }

  const clients = state.objects.filter(
    (object): object is ClientObject => object.type === "client"
  );
  const visitedClientIds = new Set<string>();
  const clusters: {
    key: string;
    clients: ClientObject[];
    sumX: number;
    sumY: number;
  }[] = [];

  function distance(a: ClientObject, b: ClientObject) {
    const dx = a.x - b.x;
    const dy = a.y - b.y;
    return Math.sqrt(dx * dx + dy * dy);
  }

  for (const client of clients) {
    if (visitedClientIds.has(client.id)) {
      continue;
    }

    const queue = [client];
    const clusterClients: ClientObject[] = [];
    let sumX = 0;
    let sumY = 0;

    visitedClientIds.add(client.id);

    while (queue.length > 0) {
      const current = queue.shift()!;
      clusterClients.push(current);
      sumX += current.x;
      sumY += current.y;

      for (const candidate of clients) {
        if (visitedClientIds.has(candidate.id)) {
          continue;
        }

        if (distance(current, candidate) <= state.densityCellSize) {
          visitedClientIds.add(candidate.id);
          queue.push(candidate);
        }
      }
    }

    clusters.push({
      key: clusterClients
        .map((entry) => entry.id)
        .sort()
        .join("|"),
      clients: clusterClients,
      sumX,
      sumY,
    });
  }

  const autoZones: DemandZoneObject[] = [];

  for (const cluster of clusters) {
    if (cluster.clients.length < state.densityThreshold) {
      continue;
    }

    const centroidX = cluster.sumX / cluster.clients.length;
    const centroidY = cluster.sumY / cluster.clients.length;
    const maxDistanceToClient = cluster.clients.reduce((largest, client) => {
      const dx = client.x - centroidX;
      const dy = client.y - centroidY;
      return Math.max(largest, Math.sqrt(dx * dx + dy * dy));
    }, 0);

    autoZones.push(
      createDemandZoneObject(centroidX, centroidY, {
        id: `auto-demand-${cluster.key}`,
        clientIds: cluster.clients.map((clusterClient) => clusterClient.id),
        clusterKey: cluster.key,
        color: colorForCluster(cluster.key),
        intensity: state.autoZoneIntensity + cluster.clients.length - state.densityThreshold,
        label: `Demand Cluster ${cluster.clients.length}`,
        radius: Math.max(state.autoZoneRadius, Math.ceil(maxDistanceToClient + 24)),
        autoGenerated: true,
      })
    );
  }

  return autoZones;
}

export const useEditorStore = create<EditorStore>((set, get) => ({
  activeTool: "select",
  setActiveTool: (tool) => set({ activeTool: tool }),

  documentName: "untitled-scenario",
  setDocumentName: (name) => set({ documentName: name }),

  showDroneRanges: false,
  toggleDroneRanges: () =>
    set((state) => ({ showDroneRanges: !state.showDroneRanges })),

  showClientDroneLinks: false,
  toggleClientDroneLinks: () =>
    set((state) => ({ showClientDroneLinks: !state.showClientDroneLinks })),

  selectedObjectId: null,
  selectedObjectIds: [],
  setSelectedObjectId: (id) =>
    set({
      selectedObjectId: id,
      selectedObjectIds: id ? [id] : [],
    }),
  setSelectedObjectIds: (ids) =>
    set({
      selectedObjectId: ids.length === 1 ? ids[0] : null,
      selectedObjectIds: ids,
    }),
  clearSelection: () => set({ selectedObjectId: null, selectedObjectIds: [] }),

  objects: [],
  clipboardObjects: [],
  addObject: (object) =>
    set((state) => ({
      objects: [...state.objects, object],
    })),
  addObjects: (objects) =>
    set((state) => ({
      objects: [...state.objects, ...objects],
    })),

  updateObject: (id, patch) =>
    set((state) => ({
      objects: state.objects.map((obj) =>
        obj.id === id ? ({ ...obj, ...patch } as EditorObject) : obj
      ),
    })),
  updateObjectsById: (ids, updater) =>
    set((state) => ({
      objects: state.objects.map((obj) =>
        ids.includes(obj.id) ? ({ ...obj, ...updater(obj) } as EditorObject) : obj
      ),
    })),

  removeObject: (id) =>
    set((state) => {
      const nextSelectedIds = state.selectedObjectIds.filter((selectedId) => selectedId !== id);
      return {
        objects: state.objects.filter((obj) => obj.id !== id),
        selectedObjectIds: nextSelectedIds,
        selectedObjectId: nextSelectedIds.length === 1 ? nextSelectedIds[0] : null,
      };
    }),
  removeSelectedObjects: () =>
    set((state) => ({
      objects: state.objects.filter((obj) => !state.selectedObjectIds.includes(obj.id)),
      selectedObjectIds: [],
      selectedObjectId: null,
    })),
  copySelectedObjects: () =>
    set((state) => ({
      clipboardObjects: state.objects
        .filter((obj) => state.selectedObjectIds.includes(obj.id))
        .map((obj) => ({ ...obj })),
    })),
  pasteClipboard: () => {
    const { clipboardObjects } = get();
    if (clipboardObjects.length === 0) {
      return;
    }

    const pastedObjects = clipboardObjects.map((object) =>
      cloneEditorObject(object, {
        offsetX: 24,
        offsetY: 24,
      })
    );

    set((state) => ({
      objects: [...state.objects, ...pastedObjects],
      selectedObjectIds: pastedObjects.map((object) => object.id),
      selectedObjectId: pastedObjects.length === 1 ? pastedObjects[0].id : null,
    }));
  },

  densityCellSize: 120,
  setDensityCellSize: (value) =>
    set({
      densityCellSize: Math.max(1, Math.round(value) || 1),
    }),

  densityThreshold: 3,
  setDensityThreshold: (value) =>
    set({
      densityThreshold: Math.max(2, Math.round(value) || 2),
    }),

  autoZoneRadius: 80,
  setAutoZoneRadius: (value) =>
    set({
      autoZoneRadius: Math.max(20, Math.round(value) || 20),
    }),

  autoZoneIntensity: 10,
  setAutoZoneIntensity: (value) =>
    set({
      autoZoneIntensity: Math.max(1, Math.round(value) || 1),
    }),

  autoDemandZonesEnabled: false,
  toggleAutoDemandZones: () =>
    set((state) => ({
      autoDemandZonesEnabled: !state.autoDemandZonesEnabled,
    })),

  resetDocument: () => {
    const empty = createEmptyEditorDocument();
    set({
      activeTool: "select",
      documentName: empty.name,
      showDroneRanges: empty.view.showDroneRanges,
      showClientDroneLinks: empty.view.showClientDroneLinks,
      selectedObjectId: null,
      selectedObjectIds: [],
      objects: empty.objects,
      clipboardObjects: [],
      densityCellSize: empty.view.densityCellSize,
      densityThreshold: empty.view.densityThreshold,
      autoZoneRadius: empty.view.autoZoneRadius,
      autoZoneIntensity: empty.view.autoZoneIntensity,
      autoDemandZonesEnabled: empty.view.autoDemandZonesEnabled,
    });
  },

  replaceFromDocument: (doc) => {
    set({
      activeTool: "select",
      documentName: doc.name,
      showDroneRanges: doc.view.showDroneRanges,
      showClientDroneLinks: doc.view.showClientDroneLinks,
      selectedObjectId: null,
      selectedObjectIds: [],
      objects: doc.objects,
      clipboardObjects: [],
      densityCellSize: doc.view.densityCellSize,
      densityThreshold: doc.view.densityThreshold,
      autoZoneRadius: doc.view.autoZoneRadius,
      autoZoneIntensity: doc.view.autoZoneIntensity,
      autoDemandZonesEnabled: doc.view.autoDemandZonesEnabled,
    });
  },

  exportToDocument: () => {
    const state = get();
    return {
      version: 1,
      name: state.documentName,
      savedAt: new Date().toISOString(),
      canvas: {
        width: 2000,
        height: 1200,
      },
      objects: state.objects,
      view: {
        showDroneRanges: state.showDroneRanges,
        showClientDroneLinks: state.showClientDroneLinks,
        densityCellSize: state.densityCellSize,
        densityThreshold: state.densityThreshold,
        autoZoneRadius: state.autoZoneRadius,
        autoZoneIntensity: state.autoZoneIntensity,
        autoDemandZonesEnabled: state.autoDemandZonesEnabled,
      },
    };
  },
}));
