import { useRef, useState } from "react";

import { createObjectFromTool } from "../../app/objectFactory";
import {
  computeAutoDemandZones,
  useEditorStore,
  type EditorObject,
} from "../../app/editorStore";

type DragState =
  | {
      objectIds: string[];
      startPointerX: number;
      startPointerY: number;
      initialPositions: Record<string, { x: number; y: number }>;
    }
  | null;

type ResizeState =
  | {
      objectId: string;
      mode: "building-size" | "drone-range" | "zone-radius" | "wall-length";
    }
  | null;

type SelectionBoxState =
  | {
      startX: number;
      startY: number;
      currentX: number;
      currentY: number;
    }
  | null;

function ObjectLabel({ text }: { text: string }) {
  return <div className="canvas-object-label">{text}</div>;
}

function Handle({
  x,
  y,
  onMouseDown,
}: {
  x: number;
  y: number;
  onMouseDown: (e: React.MouseEvent<HTMLDivElement>) => void;
}) {
  return (
    <div
      className="resize-handle"
      style={{
        position: "absolute",
        left: x,
        top: y,
        transform: "translate(-50%, -50%)",
      }}
      onMouseDown={onMouseDown}
    />
  );
}

function getObjectBounds(object: EditorObject) {
  switch (object.type) {
    case "drone":
      return {
        left: object.x - 11,
        top: object.y - 11,
        right: object.x + 11,
        bottom: object.y + 11,
      };
    case "gateway":
      return {
        left: object.x - 13,
        top: object.y - 13,
        right: object.x + 13,
        bottom: object.y + 13,
      };
    case "client":
      return {
        left: object.x - 8,
        top: object.y - 8,
        right: object.x + 8,
        bottom: object.y + 8,
      };
    case "building":
      return {
        left: object.x - object.width / 2,
        top: object.y - object.height / 2,
        right: object.x + object.width / 2,
        bottom: object.y + object.height / 2,
      };
    case "wall":
      return {
        left: object.x - object.length / 2,
        top: object.y - 5,
        right: object.x + object.length / 2,
        bottom: object.y + 5,
      };
    case "tree-zone":
    case "demand-zone":
      return {
        left: object.x - object.radius,
        top: object.y - object.radius,
        right: object.x + object.radius,
        bottom: object.y + object.radius,
      };
  }
}

function isAutoGeneratedDemandZone(
  object: EditorObject
): object is Extract<EditorObject, { type: "demand-zone" }> {
  return object.type === "demand-zone" && object.autoGenerated === true;
}

function intersectsSelectionBox(
  selectionBox: NonNullable<SelectionBoxState>,
  bounds: ReturnType<typeof getObjectBounds>
) {
  const left = Math.min(selectionBox.startX, selectionBox.currentX);
  const right = Math.max(selectionBox.startX, selectionBox.currentX);
  const top = Math.min(selectionBox.startY, selectionBox.currentY);
  const bottom = Math.max(selectionBox.startY, selectionBox.currentY);

  return !(
    bounds.right < left ||
    bounds.left > right ||
    bounds.bottom < top ||
    bounds.top > bottom
  );
}

export default function CanvasViewport() {
  const canvasRef = useRef<HTMLDivElement | null>(null);
  const suppressCanvasClickRef = useRef(false);

  const activeTool = useEditorStore((s) => s.activeTool);
  const objects = useEditorStore((s) => s.objects);
  const addObject = useEditorStore((s) => s.addObject);
  const setActiveTool = useEditorStore((s) => s.setActiveTool);
  const updateObject = useEditorStore((s) => s.updateObject);
  const updateObjectsById = useEditorStore((s) => s.updateObjectsById);
  const showClientDroneLinks = useEditorStore((s) => s.showClientDroneLinks);
  const showDroneRanges = useEditorStore((s) => s.showDroneRanges);
  const densityCellSize = useEditorStore((s) => s.densityCellSize);
  const densityThreshold = useEditorStore((s) => s.densityThreshold);
  const autoZoneRadius = useEditorStore((s) => s.autoZoneRadius);
  const autoZoneIntensity = useEditorStore((s) => s.autoZoneIntensity);
  const autoDemandZonesEnabled = useEditorStore((s) => s.autoDemandZonesEnabled);
  const selectedObjectIds = useEditorStore((s) => s.selectedObjectIds);
  const setSelectedObjectId = useEditorStore((s) => s.setSelectedObjectId);
  const setSelectedObjectIds = useEditorStore((s) => s.setSelectedObjectIds);
  const clearSelection = useEditorStore((s) => s.clearSelection);

  const [dragState, setDragState] = useState<DragState>(null);
  const [resizeState, setResizeState] = useState<ResizeState>(null);
  const [selectionBox, setSelectionBox] = useState<SelectionBoxState>(null);

  function getCanvasCoordinates(clientX: number, clientY: number) {
    if (!canvasRef.current) return null;
    const rect = canvasRef.current.getBoundingClientRect();

    return {
      x: clientX - rect.left,
      y: clientY - rect.top,
    };
  }

  function distance(ax: number, ay: number, bx: number, by: number) {
    return Math.sqrt((ax - bx) ** 2 + (ay - by) ** 2);
  }

  function createFlowLine(
    clientX: number,
    clientY: number,
    droneX: number,
    droneY: number,
    offset: number
  ) {
    const dx = droneX - clientX;
    const dy = droneY - clientY;
    const length = Math.sqrt(dx ** 2 + dy ** 2) || 1;
    const normalX = (-dy / length) * offset;
    const normalY = (dx / length) * offset;

    return {
      x1: clientX + normalX,
      y1: clientY + normalY,
      x2: droneX + normalX,
      y2: droneY + normalY,
    };
  }

  function handleCanvasClick(event: React.MouseEvent<HTMLDivElement>) {
    if (suppressCanvasClickRef.current) {
      suppressCanvasClickRef.current = false;
      return;
    }

    if (dragState || resizeState || selectionBox) return;

    const coords = getCanvasCoordinates(event.clientX, event.clientY);
    if (!coords) return;

    if (activeTool === "select") {
      clearSelection();
      return;
    }

    const newObject = createObjectFromTool(activeTool, coords.x, coords.y);
    if (!newObject) return;

    addObject(newObject);
    setSelectedObjectId(newObject.id);
    setActiveTool("select");
  }

  function handleCanvasMouseDown(event: React.MouseEvent<HTMLDivElement>) {
    if (event.target !== event.currentTarget || activeTool !== "select") {
      return;
    }

    const coords = getCanvasCoordinates(event.clientX, event.clientY);
    if (!coords) return;

    setSelectionBox({
      startX: coords.x,
      startY: coords.y,
      currentX: coords.x,
      currentY: coords.y,
    });
  }

  function handleMouseDownObject(
    event: React.MouseEvent<HTMLDivElement>,
    object: EditorObject
  ) {
    if (isAutoGeneratedDemandZone(object)) {
      return;
    }

    event.stopPropagation();

    if (activeTool !== "select") {
      setSelectedObjectId(object.id);
      return;
    }

    const coords = getCanvasCoordinates(event.clientX, event.clientY);
    if (!coords) return;

    const dragIds = selectedObjectIds.includes(object.id) ? selectedObjectIds : [object.id];
    if (!selectedObjectIds.includes(object.id)) {
      setSelectedObjectIds([object.id]);
    }

    const initialPositions = Object.fromEntries(
      objects
        .filter((candidate) => dragIds.includes(candidate.id))
        .map((candidate) => [candidate.id, { x: candidate.x, y: candidate.y }])
    );

    setDragState({
      objectIds: dragIds,
      startPointerX: coords.x,
      startPointerY: coords.y,
      initialPositions,
    });
  }

  function startResize(
    event: React.MouseEvent<HTMLDivElement>,
    objectId: string,
    mode: "building-size" | "drone-range" | "zone-radius" | "wall-length"
  ) {
    event.stopPropagation();
    event.preventDefault();
    setResizeState({ objectId, mode });
  }

  function handleMouseMove(event: React.MouseEvent<HTMLDivElement>) {
    const coords = getCanvasCoordinates(event.clientX, event.clientY);
    if (!coords) return;

    if (selectionBox) {
      setSelectionBox({
        ...selectionBox,
        currentX: coords.x,
        currentY: coords.y,
      });
      return;
    }

    if (dragState) {
      const deltaX = coords.x - dragState.startPointerX;
      const deltaY = coords.y - dragState.startPointerY;

      updateObjectsById(dragState.objectIds, (object) => {
        const initialPosition = dragState.initialPositions[object.id];
        return {
          x: initialPosition.x + deltaX,
          y: initialPosition.y + deltaY,
        };
      });
      return;
    }

    if (resizeState) {
      const object = objects.find((obj) => obj.id === resizeState.objectId);
      if (!object) return;

      if (resizeState.mode === "building-size" && object.type === "building") {
        const nextWidth = Math.max(30, Math.abs(coords.x - object.x) * 2);
        const nextHeight = Math.max(30, Math.abs(coords.y - object.y) * 2);
        updateObject(object.id, {
          width: Math.round(nextWidth),
          height: Math.round(nextHeight),
        });
        return;
      }

      if (resizeState.mode === "drone-range" && object.type === "drone") {
        const nextRange = Math.max(20, distance(object.x, object.y, coords.x, coords.y));
        updateObject(object.id, { radioRange: Math.round(nextRange) });
        return;
      }

      if (
        resizeState.mode === "zone-radius" &&
        (object.type === "tree-zone" || object.type === "demand-zone")
      ) {
        const nextRadius = Math.max(10, distance(object.x, object.y, coords.x, coords.y));
        updateObject(object.id, { radius: Math.round(nextRadius) });
        return;
      }

      if (resizeState.mode === "wall-length" && object.type === "wall") {
        const nextLength = Math.max(20, coords.x - object.x + object.length / 2);
        updateObject(object.id, { length: Math.round(nextLength) });
      }
    }
  }

  function endInteractions() {
    if (selectionBox) {
      const nextSelectedIds = objects
        .filter(
          (object) =>
            !isAutoGeneratedDemandZone(object) &&
            intersectsSelectionBox(selectionBox, getObjectBounds(object))
        )
        .map((object) => object.id);
      setSelectedObjectIds(nextSelectedIds);
      setSelectionBox(null);
      suppressCanvasClickRef.current = true;
    }

    if (dragState) {
      setDragState(null);
      suppressCanvasClickRef.current = true;
    }
    if (resizeState) {
      setResizeState(null);
      suppressCanvasClickRef.current = true;
    }
  }

  const autoDemandZones = computeAutoDemandZones({
    objects,
    densityCellSize,
    densityThreshold,
    autoZoneRadius,
    autoZoneIntensity,
    autoDemandZonesEnabled,
  });
  const selectedObjects = objects.filter((obj) => selectedObjectIds.includes(obj.id));
  const selectedObject = selectedObjects.length === 1 ? selectedObjects[0] : null;
  const clientZoneColorById = new Map<string, string>();

  for (const zone of autoDemandZones) {
    for (const clientId of zone.clientIds ?? []) {
      if (zone.color) {
        clientZoneColorById.set(clientId, zone.color);
      }
    }
  }

  const drones = objects.filter(
    (object): object is Extract<EditorObject, { type: "drone" }> =>
      object.type === "drone"
  );
  const clients = objects.filter(
    (object): object is Extract<EditorObject, { type: "client" }> =>
      object.type === "client"
  );

  const visibleLinks = showClientDroneLinks
    ? clients.flatMap((client) =>
        drones
          .filter(
            (drone) =>
              distance(client.x, client.y, drone.x, drone.y) <= drone.radioRange
          )
          .map((drone) => ({ client, drone }))
      )
    : [];

  return (
    <main className="canvas-viewport">
      <div className="canvas-header">
        <span>Canvas</span>
        <span>
          Active Tool: <strong>{activeTool}</strong>
        </span>
      </div>

      <div
        ref={canvasRef}
        className="canvas-surface"
        onClick={handleCanvasClick}
        onMouseDown={handleCanvasMouseDown}
        onMouseMove={handleMouseMove}
        onMouseUp={endInteractions}
        onMouseLeave={endInteractions}
      >
        <div className="grid-overlay" />

        {visibleLinks.length > 0 && (
          <svg className="link-overlay" aria-hidden="true">
            {visibleLinks.map(({ client, drone }) => {
              const forwardLine = createFlowLine(
                client.x,
                client.y,
                drone.x,
                drone.y,
                -3
              );
              const reverseLine = createFlowLine(
                client.x,
                client.y,
                drone.x,
                drone.y,
                3
              );

              return (
                <g key={`${client.id}-${drone.id}`}>
                  <line
                    className="flow-line flow-line--forward"
                    x1={forwardLine.x1}
                    y1={forwardLine.y1}
                    x2={forwardLine.x2}
                    y2={forwardLine.y2}
                  />
                  <line
                    className="flow-line flow-line--reverse"
                    x1={reverseLine.x1}
                    y1={reverseLine.y1}
                    x2={reverseLine.x2}
                    y2={reverseLine.y2}
                  />
                </g>
              );
            })}
          </svg>
        )}

        {selectionBox && (
          <div
            className="selection-box"
            style={{
              left: Math.min(selectionBox.startX, selectionBox.currentX),
              top: Math.min(selectionBox.startY, selectionBox.currentY),
              width: Math.abs(selectionBox.currentX - selectionBox.startX),
              height: Math.abs(selectionBox.currentY - selectionBox.startY),
            }}
          />
        )}

        {autoDemandZones.map((object) => (
          <div key={object.id}>
            <div
              style={{
                position: "absolute",
                left: object.x,
                top: object.y,
                transform: "translate(-50%, -50%)",
                width: object.radius * 2,
                height: object.radius * 2,
                borderRadius: "50%",
                background: `${object.color ?? "#ef4444"}22`,
                outline: `1.5px dashed ${object.color ?? "#ef4444"}99`,
                pointerEvents: "none",
              }}
            >
              <ObjectLabel text={object.label} />
            </div>
          </div>
        ))}

        {objects.map((object) => {
          const isSelected = selectedObjectIds.includes(object.id);
          const isSingleSelected = selectedObject?.id === object.id;

          const commonStyle: React.CSSProperties = {
            position: "absolute",
            left: object.x,
            top: object.y,
            transform: "translate(-50%, -50%)",
            border: isSelected ? "2px solid #60a5fa" : "1px solid #0f172a",
            boxShadow: isSelected ? "0 0 0 3px rgba(96, 165, 250, 0.16)" : "none",
            cursor:
              activeTool === "select" && !isAutoGeneratedDemandZone(object)
                ? "grab"
                : "default",
            userSelect: "none",
            pointerEvents: "auto",
          };

          const sharedProps = {
            key: object.id,
            title: `${object.label} (${object.id})`,
            onMouseDown: (e: React.MouseEvent<HTMLDivElement>) =>
              handleMouseDownObject(e, object),
          };

          switch (object.type) {
            case "drone":
              return (
                <div key={object.id}>
                  {showDroneRanges && (
                    <div
                      className="range-visual"
                      style={{
                        left: object.x,
                        top: object.y,
                        width: object.radioRange * 2,
                        height: object.radioRange * 2,
                      }}
                    />
                  )}

                  {isSingleSelected && showDroneRanges && (
                    <Handle
                      x={object.x + object.radioRange}
                      y={object.y}
                      onMouseDown={(e) => startResize(e, object.id, "drone-range")}
                    />
                  )}

                  <div
                    {...sharedProps}
                    style={{
                      ...commonStyle,
                      width: 22,
                      height: 22,
                      borderRadius: "50%",
                      background: "#38bdf8",
                    }}
                  >
                    <ObjectLabel text={object.label} />
                  </div>
                </div>
              );

            case "gateway":
              return (
                <div
                  {...sharedProps}
                  style={{
                    ...commonStyle,
                    width: 26,
                    height: 26,
                    borderRadius: 6,
                    background: "#f59e0b",
                  }}
                >
                  <ObjectLabel text={object.label} />
                </div>
              );

            case "client":
              return (
                <div
                  {...sharedProps}
                  style={{
                    ...commonStyle,
                    width: 16,
                    height: 16,
                    borderRadius: "50%",
                    background: clientZoneColorById.get(object.id) ?? "#a78bfa",
                  }}
                >
                  <ObjectLabel text={object.label} />
                </div>
              );

            case "building":
              return (
                <div key={object.id}>
                  <div
                    {...sharedProps}
                    style={{
                      ...commonStyle,
                      width: object.width,
                      height: object.height,
                      borderRadius: 8,
                      background: "#c4a484",
                    }}
                  >
                    <ObjectLabel text={object.label} />
                  </div>

                  {isSingleSelected && (
                    <Handle
                      x={object.x + object.width / 2}
                      y={object.y + object.height / 2}
                      onMouseDown={(e) => startResize(e, object.id, "building-size")}
                    />
                  )}
                </div>
              );

            case "wall":
              return (
                <div key={object.id}>
                  <div
                    {...sharedProps}
                    style={{
                      ...commonStyle,
                      width: object.length,
                      height: 10,
                      borderRadius: 6,
                      background: "#6b7280",
                    }}
                  >
                    <ObjectLabel text={object.label} />
                  </div>

                  {isSingleSelected && (
                    <Handle
                      x={object.x + object.length / 2}
                      y={object.y}
                      onMouseDown={(e) => startResize(e, object.id, "wall-length")}
                    />
                  )}
                </div>
              );

            case "tree-zone":
              return (
                <div key={object.id}>
                  <div
                    style={{
                      ...commonStyle,
                      width: object.radius * 2,
                      height: object.radius * 2,
                      borderRadius: "50%",
                      background: "rgba(34, 197, 94, 0.45)",
                      pointerEvents: "none",
                    }}
                  >
                    <ObjectLabel text={object.label} />
                  </div>

                  <div
                    {...sharedProps}
                    style={{
                      position: "absolute",
                      left: object.x,
                      top: object.y,
                      transform: "translate(-50%, -50%)",
                      width: 18,
                      height: 18,
                      borderRadius: "50%",
                      border: isSelected ? "2px solid #60a5fa" : "1px solid #0f172a",
                      boxShadow: isSelected ? "0 0 0 3px rgba(96, 165, 250, 0.16)" : "none",
                      background: "#22c55e",
                      cursor: activeTool === "select" ? "grab" : "pointer",
                    }}
                  />

                  {isSingleSelected && (
                    <Handle
                      x={object.x + object.radius}
                      y={object.y}
                      onMouseDown={(e) => startResize(e, object.id, "zone-radius")}
                    />
                  )}
                </div>
              );

            case "demand-zone":
              return (
                <div key={object.id}>
                  <div
                    style={{
                      ...commonStyle,
                      width: object.radius * 2,
                      height: object.radius * 2,
                      borderRadius: "50%",
                      background: "rgba(239, 68, 68, 0.25)",
                      outline: "2px dashed rgba(239, 68, 68, 0.8)",
                      pointerEvents: "none",
                    }}
                  >
                    <ObjectLabel text={object.label} />
                  </div>

                  <div
                    {...sharedProps}
                    style={{
                      position: "absolute",
                      left: object.x,
                      top: object.y,
                      transform: "translate(-50%, -50%)",
                      width: 18,
                      height: 18,
                      borderRadius: "50%",
                      border: isSelected ? "2px solid #60a5fa" : "1px solid #7f1d1d",
                      boxShadow: isSelected ? "0 0 0 3px rgba(96, 165, 250, 0.16)" : "none",
                      background: "#ef4444",
                      cursor: activeTool === "select" ? "grab" : "pointer",
                    }}
                  />

                  {isSingleSelected && (
                    <Handle
                      x={object.x + object.radius}
                      y={object.y}
                      onMouseDown={(e) => startResize(e, object.id, "zone-radius")}
                    />
                  )}
                </div>
              );

            default:
              return null;
          }
        })}

        {objects.length === 0 && (
          <div className="canvas-placeholder">
            <p>2D Map Area</p>
            <p>Pick a tool and click to place objects.</p>
          </div>
        )}

        {selectedObjectIds.length > 0 && (
          <div className="selection-readout">
            {selectedObjectIds.length === 1 && selectedObject
              ? `Selected: ${selectedObject.label} (${selectedObject.type})`
              : `Selected: ${selectedObjectIds.length} objects`}
          </div>
        )}
      </div>
    </main>
  );
}
